name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build Windows executable
      run: |
        GOOS=windows GOARCH=amd64 go build -o ps-claude.exe
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ps-claude-windows
        path: ps-claude.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build Windows executable
      run: |
        GOOS=windows GOARCH=amd64 go build -o ps-claude.exe
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ps-claude.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}